#! /usr/bin/env bash

set -uo pipefail

export_dirpath="${HOME}/.defaults"
local_export_dirpath="${export_dirpath}/local"
remote_export_dirpath="${export_dirpath}/remote"
local_global_machine_export_dirpath="${local_export_dirpath}/global"
local_user_machine_export_dirpath="${local_export_dirpath}/user"
remote_global_machine_export_dirpath="${remote_export_dirpath}/global"
remote_user_machine_export_dirpath="${remote_export_dirpath}/user"

# ACTION_CLEAN=0
# ACTION_READ=0

# while [[ ${#} -ne 0 ]] && [[ "${1}" != "" ]]; do
#   case "${1}" in
#     build )
#       ACTION_BUILD=1
#       shift
#     ;;

#     upload )
#       ACTION_UPLOAD=1
#       shift
#     ;;

#     prod )
#       ACTION_TARGET="prod"
#       shift
#     ;;

#     * )
#       >&2 echo "Unknown action [${1}]."
#       shift
#   esac
# done


# arg_1=""

# if [[ ${#} -eq 1 ]]; then
#     arg_1="${1}"
# fi

# if [[ "${arg_1}" == "-" ]] || [[ "${arg_1}" == "--help" ]]; then
#     >&2 echo
#     >&2 echo "    -d | --debug"
#     >&2 echo "        Don't do anything, just print info."
#     exit 1
# elif [[ "${arg_1}" == "-d" ]] || [[ "${arg_1}" == "--debug" ]]; then
#     DEBUG=1
# fi

function delete_or_create_dir() {
    local dirpath="${1}"

    # pokud existují adresáře, tak nabídnout je smazat
    if [[ -d "${dirpath}" ]]; then
        echo
        echo "Directory '${dirpath}' exists!"
    else
        mkdir -p "${dirpath}"
    fi
}

function export_defaults() {
    local namespace="${1}"
    local domain

    # upravit, aby se neduplikoval kód

    if [[ "${namespace}" == "global" ]]; then
        for domain in $(sudo defaults domains); do
            domain="${domain//,/}"
            local local_domain_plist="${local_global_machine_export_dirpath}/${domain}.plist"

            echo
            echo "${domain}"

            sudo defaults read "${domain}" > "${local_domain_plist}"
        done
    else
        for domain in $(defaults domains); do
            domain="${domain//,/}"
            local local_domain_plist="${local_user_machine_export_dirpath}/${domain}.plist"

            echo
            echo "${domain}"

            defaults read "${domain}" > "${local_domain_plist}"
        done
    fi
}

if [[ ! -d "${export_dirpath}" ]]; then
    echo
    echo "Directory '${export_dirpath}' doesn't exist, creating..."

    mkdir -p "${export_dirpath}"
fi

delete_or_create_dir "${local_global_machine_export_dirpath}"
delete_or_create_dir "${local_user_machine_export_dirpath}"
delete_or_create_dir "${remote_global_machine_export_dirpath}"
delete_or_create_dir "${remote_user_machine_export_dirpath}"


export_defaults "global"
export_defaults "user"
